#!/usr/bin/env perl -w
# Quick kludge to turn Chirp <http://chirp.danplanet.com/> CSV files into JSONP structures so we can load them.
#
# No particular reason for choosing Chirp other than it was a source of machine-readable station data to experiment with.

use JSON qw(encode_json);

my @filedata;
for my $file (@ARGV) {
  open F, $file or die $!;
  my @out;
  push @filedata, \@out;
  while (<F>) {
    s/[\r\n]*$//;
    push @out, [split ',', $_];
  }
}

print 'sdr_data(', encode_json(\@filedata), ");\n";
